# Generated by Django 2.1 on 2020-12-09 21:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='task',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_title', models.CharField(max_length=50)),
                ('task_desc', models.TextField()),
                ('pub_date', models.DateField(auto_now=True)),
            ],
        ),
    ]
